version: "3.9"
services:
  simgec-backend:
    image: simgec-backend:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      JWT_SECRET: "${JWT_SECRET}"
      DATABASE_PATH: /usr/src/app/data/simgec.db
    volumes:
      - ./data:/usr/src/app/data:rw
      - ./logs:/usr/src/app/logs:rw
    restart: unless-stopped
